Vagrant.configure("2") do |config|
  config.vm.box = "bento/oracle-8"

  # Set the desired IP address for the VM
  config.vm.network "private_network", type: "static", ip: "192.168.33.10"

  # Provision the VM using Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/libs/create_user_and_update.yml"
  end

  # Additional Ansible provisioners for enforcing SELinux and installing nginx
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/libs/enforce_selinux.yml"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/libs/install_nginx.yml"
  end

  # Forward port 80 from the guest to the host
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
